ClearSkyLettings/Models/Property.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ClearSkyLettings.Models
{
    public class Property
    {
        public int ID { get; set; }

        [Display(Name ="Address")]
        public string Title { get; set; }

        [Display(Name = "Listing Date")]
        [DataType(DataType.Date)]
        public DateTime ListingDate { get; set; }

        [Display(Name = "Available From")]
        [DataType(DataType.Date)]
        public DateTime AvailableDate { get; set; }

        public string Type { get; set; }

        public int Beds { get; set; }

        public int Bathrooms { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal Rent { get; set; }
    }
}

ClearSkyLettings/Controllers/EnquiriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClearSkyLettings.Data;
using ClearSkyLettings.Models;

namespace ClearSkyLettings.Controllers
{
    public class EnquiriesController : Controller
    {
        private readonly ClearSkyLettingsEnquiryContext _contextEnquiry;

        public EnquiriesController(ClearSkyLettingsEnquiryContext contextEnquiry)
        {
            _contextEnquiry = contextEnquiry;
        }

        // GET: Enquiries
        public async Task<IActionResult> Index()
        {            
            return View(await _contextEnquiry.Enquiry.ToListAsync());
        }

        // GET: Enquiries/Success
        public async Task<IActionResult> Success()
        {
            return View(await _contextEnquiry.Enquiry.ToListAsync());
        }

        // GET: Enquiries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enquiry = await _contextEnquiry.Enquiry
                .FirstOrDefaultAsync(m => m.ID == id);
            if (enquiry == null)
            {
                return NotFound();
            }

            return View(enquiry);
        }

        // GET: Enquiries/Create
        public IActionResult Create()
        {
            return View();
        }        
        
        // POST: Enquiries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,FirstName,LastName,Email,Subject,Message,PropertyName")] Enquiry enquiry)
        {
            if (ModelState.IsValid)
            {
                _contextEnquiry.Add(enquiry);
                await _contextEnquiry.SaveChangesAsync();
                return RedirectToAction(nameof(Success));
            }            

            return View(enquiry);
        }       
    }
}

ClearSkyLettings/Controllers/PropertiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClearSkyLettings.Data;
using ClearSkyLettings.Models;
using Microsoft.AspNetCore.Authorization;

namespace ClearSkyLettings.Controllers
{
    public class PropertiesController : Controller
    {
        private readonly ClearSkyLettingsPropertyContext _context;

        public PropertiesController(ClearSkyLettingsPropertyContext context)
        {
            _context = context;
        }

        // GET: Properties
        public async Task<IActionResult> Index()
        {
            return View(await _context.Property.ToListAsync());
        }

        // GET: Properties/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Properties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,ListingDate,AvailableDate,Type,Beds,Bathrooms,Rent")] Property @property)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@property);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@property);
        }

        // GET: Properties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @property = await _context.Property.FindAsync(id);
            if (@property == null)
            {
                return NotFound();
            }
            return View(@property);
        }

        // POST: Properties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,ListingDate,AvailableDate,Type,Beds,Bathrooms,Rent")] Property @property)
        {
            if (id != @property.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@property);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PropertyExists(@property.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@property);
        }

        // GET: Properties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @property = await _context.Property
                .FirstOrDefaultAsync(m => m.ID == id);
            if (@property == null)
            {
                return NotFound();
            }

            return View(@property);
        }

        // POST: Properties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @property = await _context.Property.FindAsync(id);
            _context.Property.Remove(@property);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Properties/Enquiry/5
        public async Task<IActionResult> Enquiry(int? id)
        {
            if (id == null) { return NotFound(); }           

            var @property = await _context.Property.FirstOrDefaultAsync(m => m.ID == id);

            if (@property == null) { return NotFound(); }            

            return View(@property);
        }

        private bool PropertyExists(int id)
        {
            return _context.Property.Any(e => e.ID == id);
        }
    }
}

ClearSkyLettings/Views/Properties/Create.cshtml
@model ClearSkyLettings.Models.Property

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Property</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ListingDate" class="control-label"></label>
                <input asp-for="ListingDate" class="form-control" />
                <span asp-validation-for="ListingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AvailableDate" class="control-label"></label>
                <input asp-for="AvailableDate" class="form-control" />
                <span asp-validation-for="AvailableDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Beds" class="control-label"></label>
                <input asp-for="Beds" class="form-control" />
                <span asp-validation-for="Beds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bathrooms" class="control-label"></label>
                <input asp-for="Bathrooms" class="form-control" />
                <span asp-validation-for="Bathrooms" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rent" class="control-label"></label>
                <input asp-for="Rent" class="form-control" />
                <span asp-validation-for="Rent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Properties</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ClearSkyLettings/Views/Properties/Delete.cshtml
@model ClearSkyLettings.Models.Property

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Property</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ListingDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ListingDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AvailableDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AvailableDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Beds)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Beds)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bathrooms)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bathrooms)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rent)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to Properties</a>
    </form>
</div>

ClearSkyLettings/Views/Properties/Edit.cshtml
@model ClearSkyLettings.Models.Property

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Property</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ListingDate" class="control-label"></label>
                <input asp-for="ListingDate" class="form-control" />
                <span asp-validation-for="ListingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AvailableDate" class="control-label"></label>
                <input asp-for="AvailableDate" class="form-control" />
                <span asp-validation-for="AvailableDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Beds" class="control-label"></label>
                <input asp-for="Beds" class="form-control" />
                <span asp-validation-for="Beds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bathrooms" class="control-label"></label>
                <input asp-for="Bathrooms" class="form-control" />
                <span asp-validation-for="Bathrooms" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rent" class="control-label"></label>
                <input asp-for="Rent" class="form-control" />
                <span asp-validation-for="Rent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Properties</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ClearSkyLettings/Views/Properties/Index.cshtml
@model IEnumerable<ClearSkyLettings.Models.Property>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Properties</h1>

@if (User.Identity.IsAuthenticated)
{
    if (User.IsInRole("Admin"))
    {
        <p>
            <a asp-action="Create">Create New</a>
        </p>
    }
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ListingDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AvailableDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Beds)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bathrooms)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rent)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ListingDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvailableDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Beds)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bathrooms)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rent)
            </td>
            @if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("Admin"))
                {
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>
                }
                else
                {
                    <td>
                        @*<a asp-action="Create" asp-controller="Enquiries" asp-route-id="@item.ID">Enquire</a>*@
                        <a asp-action="Create" asp-controller="Enquiries" asp-="">Enquire</a>
                    </td>
                }
            }
        </tr>
        }
    </tbody>
</table>